### ISSUE TITLE
OPI needs cluster-wide access to resources

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/eirini#110]
### Description

The OPI service shouldn't require any cluster-wide permissions.

### Steps to reproduce

Using a serviceaccount with access to the eirini namespace:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-role
  namespace: {{ .Values.eirini.opi.namespace }}
rules:
...
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - update
  - delete
  - list
...
```

### What was expected to happen

OPI should work.

### What actually happened

Got an error.

### Suggested fix (optional)

Only work with StatefulSets in the eirini namespace.

### Additional information (optional)

```
{"timestamp":"2020-09-04T22:26:15.145143385Z","level":"error","so 
 urce":"handler","message":"handler.list-apps.bifrost-failed","dat 
 a":{"error":"failed to list desired LRPs: failed to list stateful 
 sets: statefulsets.apps is forbidden: User \"system:serviceaccoun 
 t:kubecf:opi\" cannot list resource \"statefulsets\" in API group 
  \"apps\" at the cluster scope","session":"57"}} 
```
